name: CI build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy Docker Image to Docker Hub.
      run: echo "Mock a deployment."
      
