# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: py_fmt_report

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest junit_xml_output
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Report Generation
      run: |
        #Fake a generator to gen junit-xml.
        python report_generator.py
    - name: Surface failing tests
      if: always()
      uses: pmeier/pytest-results-action@main
      with:
        path: results.xml
        summary: true
        display-options: fEX
        fail-on-empty: true
